export default {
    dashboard: '/dashboard',
    calculator: '/calculator',
    calculator_cdr: '/calculator/cdr',
    calculator_rcr: '/calculator/rcr',
    calculator_gems: '/calculator/gems',
    calculator_paragon: '/calculator/paragon',
    ros: '/ros',
    ros_followersettings: '/ros/followersettings',
    ros_efficiency_setting: '/ros/efficiencysettings',
    ros_rbatriggers: '/ros/rbatriggers',
    ros_troubleshooting: '/ros/troubleshooting',
    thudplugin: '/thudplugin',
    bluepost: '/bluepost',
};
